server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.clb.domain
  mapper-locations: classpath:mapper/*.xml

spring:
  profiles:
    active: dev # 可切换为pro,需要修改pro.yml文件相关配置
  cache:
    type: redis  # 不使用改为none
    redis:
      time-to-live: 3600000 # 缓存过期时间,单位ms(此处一小时)

  # 热重载排除advice文件
  devtools:
    restart:
      additional-exclude: com/clb/util/Advice.class
  # 支持控制台ansi颜色输出,乱码则禁止这项
  output:
    ansi:
      enabled: always

# 日志
logging:
  level:
    com.clb: debug
  pattern:
    dateformat: MM-dd HH:mm:ss.SSS
