server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.clb.domain
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_design
    username: root
    password: 123456
  devtools:
    restart:
      additional-exclude: com/clb/util/Advice.class

logging:
  level:
    com.clb: debug
  pattern:
    dateformat: MM-dd HH:mm:ss.SSS

